" vim: foldmethod=marker foldlevel=0
vim9script

runtime defaults.vim


set foldmethod=marker foldlevel=1
set modeline
set expandtab smarttab shiftwidth=4
set ignorecase smartcase
set number relativenumber
set wildmenu wildoptions=pum
set hlsearch
set belloff=all
set splitbelow splitright
set display=lastline,uhex laststatus=2 smoothscroll
set linebreak breakindent breakindentopt=shift:2
set viminfo=


# Custom Grepping Behavior
# {{{
&grepprg = [
    'grep',
    '--line-number',
    '--with-filename',
    '--recursive',
    '--ignore-case',
    '--perl-regexp',
    '--binary-files=without-match',
    '--exclude-dir .git',
    '--exclude-dir .cvs',
    '--exclude-dir .svn',
    '--exclude-dir .hg',
    '--exclude-dir node_modules',
    '$*'
]->join()

command! -nargs=+ GrepCustom {
    silent grep! <args>
    copen
    redraw!
}

cabbrev grep GrepCustom
# }}}


# Smart vertical/horizontal :h
# {{{
var vertical_help_threshold: number = 160
command! -nargs=1 -complete=help HelpCustom {
    var modifier: string = (
        getwininfo(win_getid())[0].width < vertical_help_threshold
            ? "horizontal" : "vertical"
    )
    execute modifier "<mods> help <args>"
}

cabbrev h HelpCustom
# }}}


g:mapleader = "\<Space>"
g:maplocalleader = "\<Space>"

nnoremap <Leader>h <Cmd>set hlsearch! hlsearch?<CR>
nnoremap <Leader>p <Cmd>set paste! paste?<CR>
nnoremap <Leader>l <Cmd>set list! list?<CR>

