set number
set hlsearch
syntax enable
filetype plugin indent on
set tabstop=4 shiftwidth=4 expandtab
set ff=unix
set wildmode=longest,list,full
set splitbelow splitright
set showcmd
let mapleader = "\\"

inoremap ;nn <Esc>/<++><Enter>:noh<Enter>"_c4l
nnoremap <Leader>n <Esc>/<++><Enter>:noh<Enter>"_c4l
nnoremap <Leader>s :!cls && shellcheck %<Enter>
nnoremap <Leader>c :!cls && compileit %<Enter>
nnoremap <Leader>Z :w !sudo tee %<Enter>

vnoremap <A-c> "+y
 noremap <A-p> "+p

autocmd BufWritePost ~/.Xresources,~/.Xdefaults !xrdb %

autocmd FileType tex inoremap ;bb <Bslash>begin{}<Esc>i
autocmd FileType tex inoremap ;ee <Esc>yyplcwend<Esc>o<++><Esc>kO

autocmd FileType html inoremap ;ee <Esc>yypl/<Esc>o<++><Esc>kO

autocmd FileType python inoremap ;ifm if<Space>__name__<Space>==<Space>"__main__":<Enter>

