#!/usr/bin/env sh

## Add this to your wm startup file.

# Terminate already running bar instances
#killall -q polybar

# Wait until the processes have been shut down
#while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
polybar main -c "$XDG_CONFIG_HOME/polybar/tests/pb1.ini" &
polybar main -c "$XDG_CONFIG_HOME/polybar/tests/pb2.ini" &
polybar main -c "$XDG_CONFIG_HOME/polybar/tests/pb3.ini"
