#! /bin/sh


rofi
    -modi drun,window \
    -show drun \
    -line-padding 4 \
    -columns 2 \
    -width 40 \
    -padding 30 \
    -hide-scrollbar \
    -show-icons \
    -drun-icon-theme "Papirus"

