
if $XDG_CONFIG_HOME == ''
    echoerr 'Please, set $XDG_CONFIG_HOME.'
    normal :q!
endif

if $XDG_DATA_HOME == ''
    echoerr 'Please, set $XDG_DATA_HOME.'
    normal :q!
endif



" Sets the location for the viminfo file
set viminfo+=n$XDG_DATA_HOME/vim/viminfo

" So that Vim complies to the XDG specs
set runtimepath=$VIMRUNTIME
set runtimepath+=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after


packadd termdebug


" Must run first
runtime plugs.vim
" Must run after plugs.vim
runtime funcs.vim
" Must run after plugs.vim
runtime sets.vim
" Must run after funcs.vim
runtime maps.vim


augroup reload_when_save
    autocmd!
    autocmd BufWritePost ~/.Xresources,~/.Xdefaults !xrdb %
    autocmd BufWritePost ~/.config/vim/vimrc source %
    autocmd BufWritePost ~/.config/vim/abbr/* source %
augroup END

augroup options_per_ftype
    autocmd!
    " When wrapping markdown lines, indent by 2 spaces instead of 4
    autocmd FileType markdown setlocal breakindentopt=shift:2
    autocmd FileType markdown setlocal ignorecase infercase
augroup END

augroup sess_on_crash | autocmd! VimLeave * call SaveDeathSession() | augroup END

