
if $XDG_CONFIG_HOME ==# ''
    echoerr 'Please, set $XDG_CONFIG_HOME.'
    quit!
endif

if $XDG_DATA_HOME ==# ''
    echoerr 'Please, set $XDG_DATA_HOME.'
    quit!
endif

let g:vimrc_home_dir = $XDG_CONFIG_HOME .. "/vim"



" Sets the location for the viminfo file
set viminfo+=n$XDG_DATA_HOME/vim/viminfo

" So that Vim complies to the XDG specs
set runtimepath=$VIMRUNTIME
set runtimepath+=/usr/share/vim/vimfiles
let &runtimepath .= "," .. g:vimrc_home_dir
let &runtimepath .= "," .. g:vimrc_home_dir .. "/after"

let &runtimepath .= ",/home/bruno/cln/vim-markdown-ext/"


packadd termdebug


" Must run first
runtime plugs.vim
" Must run after plugs.vim
runtime funcs.vim
" Must run after plugs.vim
runtime sets.vim
" Must run after funcs.vim
runtime maps.vim


augroup reload_when_save
    autocmd!
    autocmd BufWritePost ~/.Xresources,~/.Xdefaults !xrdb %
    autocmd BufWritePost ~/.config/vim/vimrc source %
    autocmd BufWritePost ~/.config/vim/abbr/* source %
augroup END

augroup options_per_ftype
    autocmd!
    " When wrapping markdown lines, indent by 2 spaces instead of 4
    autocmd FileType markdown setlocal breakindentopt=shift:2
    autocmd FileType markdown setlocal ignorecase infercase
augroup END

augroup sess_on_crash | autocmd! VimLeave * call SaveDeathSession() | augroup END

