
if $XDG_CONFIG_HOME ==# ''
    echoerr 'Please, set $XDG_CONFIG_HOME.'
    quit!
endif

if $XDG_DATA_HOME ==# ''
    echoerr 'Please, set $XDG_DATA_HOME.'
    quit!
endif

if $XDG_CACHE_HOME ==# ''
    echoerr 'Please, set $XDG_DATA_HOME.'
    quit!
endif

" So that Vim complies to the XDG specs
let g:vimrc_home_dir = $XDG_CONFIG_HOME .. "/vim"



" :help viminfo-file
set viminfo='100,<50,s10,/10,h
set viminfofile=$XDG_CACHE_HOME/vim/viminfo

set runtimepath=
let &runtimepath .= "," .. g:vimrc_home_dir
set runtimepath+=/usr/share/vim/vimfiles
set runtimepath+=$VIMRUNTIME
set runtimepath+=/usr/share/vim/vimfiles/after
let &runtimepath .= "," .. g:vimrc_home_dir .. "/after"


runtime! ftplugin/man.vim


nnoremap <SPACE> <Nop>
let mapleader = "\<Space>"

" Must run first
runtime plugs.vim
" Must run after plugs.vim
runtime funcs.vim
" Must run after plugs.vim
runtime sets.vim
" Must run after funcs.vim
runtime maps.vim


augroup options_per_ftype
    autocmd!
    " When wrapping markdown lines, indent by 2 spaces instead of 4
    autocmd FileType markdown setlocal breakindentopt=shift:2
    autocmd FileType markdown setlocal ignorecase infercase
augroup END

command! -nargs=+ Grep execute 'silent lgrep! <args>' | lopen
command! -nargs=+ Hg execute 'helpgrep <args>' | copen
